= Document Title
Doc Writer <doc@example.com>
:reproducible:
:listing-caption: Listing
:source-highlighter: rouge
:toc:
// Uncomment next line to add a title page (or set doctype to book)
//:title-page:
// Uncomment next line to set page size (default is A4)
//:pdf-page-size: Letter

An example of a basic https://asciidoc.org[AsciiDoc] document prepared by {author}.

== Introduction

Текст приведен в таблице <<table_01>>
[caption="Таблица {counter:table} — ", reftext="{table}"]
.Пример таблицы
[#table_02]
|===
.3+^.^h|Наружный диаметр подшипника 6+^.^h|Канавка .3+^.^h|D~2~ 5+^.^h|Установочное кольцо
2+^.^h|D~1~ 2+^.^h|A .2+^.^h|B .2+^.^h|r 2+^.^h|H .2+^.^h|C 2+^.^h|r~1~
^.^h|Номин. ^.^h|Пред. откл. ^.^h|Номин. ^.^h|Пред. откл. ^.^h|Номин. ^.^h|Пред. откл. ^.^h|Номин. ^.^h|Пред. откл.
|30
|23,2
.4+|-0.2
.6+|2.05
.4+|-0.15
.6+|1.3
.6+|0.4
|34.6
.6+|3.2
.2+|-0.1
.6+|1.10
.4+|0.4
.4+|-0.1
|32
|30.2
|39.6

|35
|33.2
|41.2
.4+|-0.2
|37
|34.8
|41.2
|40
|38.1
.2+|-0.3
.2+|-0.20
|44.5
|0.5
|-0.2

|42
|39.8
|46.2
|06
|-0.3
|===



A paragraphdfdfdf followed by an unordered list{empty}footnote:[AsciiDoc supports unordered, ordered, and description lists.] with square bullets.footnote:[You may choose from square, disc, and circle for the bullet style.]

[square]
* item 1sdsds
* item 2
* item 3

== Main

Here's how you say "`Hello, World!`" in Prawn:

.Create a basic PDF document using Prawn
[source,ruby]
----
require 'prawn'

Prawn::Document.generate 'example.pdf' do
  text 'Hello, World!'
end
----

== Conclusion

That's all, folks!
